# Generated by Django 5.2.6 on 2025-09-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoewebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproduct',
            name='title2',
            field=models.CharField(default='images/default.png', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeproduct',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
