# Generated by Django 5.2.6 on 2025-09-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoewebsite', '0005_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
