# Generated by Django 5.2.6 on 2025-09-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoewebsite', '0006_order_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
                ('price_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('image_url', models.ImageField(upload_to='images/')),
                ('colors', models.CharField(blank=True, help_text='Comma separated color hexes', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
                ('price_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('image_url', models.ImageField(upload_to='images/')),
                ('colors', models.CharField(blank=True, help_text='Comma separated color hexes', max_length=120)),
            ],
        ),
    ]
